### ISSUE TITLE
Question: Consuming the exported JSON data

### ISSUE THREAD

**Issue by SgtPooki** [darekkay/todoist-export#12]
Do you have any guides / docs on how to consume the exported JSON?

Do we use https://github.com/doist/todoist-python or is there another client that can parse this data easily?

**Comment by darekkay** [comment]
Hi @SgtPooki , thanks for the question.

The `todoist-python` library is not for processing the JSON file - it's for directly interacting with Todoist data (read/write). For example, you could use it to create a similar export as `todoist-export` does.

What is your exact goal? "Consuming" the JSON may be as easy as opening the file in a text editor. However, it's a lot of data, so you could also look for a "JSON visualizer" like the [Online JSON Viewer](http://jsonviewer.stack.hu/): paste your JSON into the `Text` tab and then switch to the `Viewer` tab:

![image](https://user-images.githubusercontent.com/3101914/108980991-93acb380-768c-11eb-8f1a-d0c5a3d48541.png)

Here you can click through the UI to get the structure overview. For example, all todos are under `items`.

For advanced insights you'll probably need to write a custom script, depending on what you're trying to achieve.

**Comment by SiddharthShyniben** [comment]
I think @SgtPooki meant how to restore the data @darekkay

**Comment by darekkay** [comment]
> I think @SgtPooki meant how to restore the data @darekkay

If that's the case, then unfortunately I am not aware of any tool. You would need to write the code yourself to import a Todoist backup.
