### ISSUE TITLE
export broken due to SSL

### ISSUE THREAD

**Issue by kparal** [darekkay/todoist-export#4]
I've been using todoist-export for months. Two weeks back, everything worked fine. Yesterday and today, export is broken. After I click `Authorize & Backup`, I get this in Firefox:

> ## Secure Connection Failed
> The connection to localhost:3000 was interrupted while the page was loading.
> The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
> Please contact the website owners to inform them of this problem.
> [Learn more…](https://support.mozilla.org/kb/what-does-your-connection-is-not-secure-mean)

I don't know if this is due to a change in Firefox, or in Todoist. But when I try Chromium, it has the same problem.

I suspect this has some connection to SSL. The "connection failed" URL is https://localhost:3000/todoist-export/?state=json&code=XXX . When I change `https` to `http` and keep the rest of the URL, I can actually retrieve the exported file!

When I look into network console, it seems that Todoist is now redirecting always to `https`, even though the [Todoist App](https://developer.todoist.com/appconsole.html) I configured should redirect to `http`. Maybe it's related to the fact that Todoist sets `Strict-Transport-Security` HTTP header. Maybe they started using HSTS lately? I'm not sure if it can be related.

Any idea how to make it work by default?

**Comment by darekkay** [comment]
@kparal Thanks for the report. As you mentioned, Todoist seems to always redirect to `https`. My [live demo](https://darekkay.com/todoist-export/) uses `https` by default, so it works fine. 

I believe, a [self-signed ssl certificate](https://stackoverflow.com/questions/21397809/create-a-trusted-self-signed-ssl-cert-for-localhost-for-use-with-express-node) should solve the problem for localhost. Feel free to open a PR if it works out for you :)

**Comment by kparal** [comment]
I can create certifications using openssl but I don't understand how to edit `app.js` according to the guide. Could you perhaps add a note to readme how to do that? Or even expect certificate files at some location, and if they are present, automatically use them?

**Comment by darekkay** [comment]
I've added an option to run a HTTPS server and updated the README (ab4120f3c93ed230364f7d5ba8d2abf800ed84b5).

**Comment by kparal** [comment]
First I had 
```
/home/kparal/programy/todoist-export/config.js:9
  ssl: {
  ^^^
SyntaxError: Unexpected identifier
```
which I solved by adding a comma after `client_secret`. Now I have
```
/home/kparal/programy/todoist-export/config.js:10
    cert: fs.readFileSync('./ssl/fullchain.pem'),
          ^

ReferenceError: fs is not defined
```
which I don't know how to solve.

**Comment by darekkay** [comment]
I forgot to require the `fs` module. Add this to the top of your `config.js` file:
```javascript
var fs = require('fs');
```

**Comment by kparal** [comment]
Thanks a lot. That works.
