### ISSUE TITLE
Package deprecation warnings - clarify minimum supported version of nodejs

### ISSUE THREAD

**Issue by JPvRiel** [darekkay/todoist-export#5]
Just FYI, has depreciation warnings when `npm install` is run (nodejs v4.2.6) nodejs on Ubuntu 16.04 LTS if installed via apt and default sources:

```
npm WARN deprecated jade@1.6.0
npm WARN deprecated constantinople@2.0.1
npm WARN deprecated transformers@2.1.0
npm WARN deprecated node-uuid@1.4.8
npm WARN deprecated hoek@0.9.1
```

Probably caused by Ubuntu LTS having an outdated version of node. Seems better if users install node via upstream nodejs,  e.g. `curl -sL https://deb.nodesource.com/setup_8.x | sudo bash -` (via https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions) instead of  just `apt install nodejs` from the distro source.

**Comment by darekkay** [comment]
A *deprecated* module means it's *not further developed*, but it's available and this application will work as it always has. Therefore, the warnings may be ignored (except for possible bugs/vulnerabilities, see #6).

This project is from 2014, so according to the [release dates](https://github.com/nodejs/Release) I must have been using **NodeJS 0.10.x** back then. You may view this as the minimum supported version. NodeJS 4 was released one year later, in 2015. 

BTW, Node 4.x reached its end-of-life, so it might be a good idea to update to at least Node 6.x anyway.
