### ISSUE TITLE
Glitch fork

### ISSUE THREAD

**Issue by mayerwin** [darekkay/todoist-export#7]
Thanks for the awesome app. I just wanted to let you know that have forked it on Glitch (really cool platform for anyone to clone, inspect code, and run it without having to set up nodejs locally), and added the ability to show a permanent backup file URL including the user token (useful if you want to automate your backups):
https://todoist-backup.glitch.me/app/

**Comment by darekkay** [comment]
Thanks, I like the backup link idea 👍 Do you mind opening a PR to get this feature back to this project? I couldn't find those changes in your GitHub fork, just in Glitch itself.

**Comment by mayerwin** [comment]
Done with https://github.com/darekkay/todoist-export/pull/8
However it would be good to put the format selector on top, and use it when generating the permanent download link (right now format=json is harcoded). Also to auto-select the link on click for easy copy pasting.

Fyi you can see the source code of the Glitch here: https://glitch.com/edit/#!/todoist-backup
But I didn't really fork it as a Git project so it wouldn't have been very helpful for you to identify the changes anyway (however it is helpful if you want to tinker with the code).
